### ISSUE TITLE
Some software doesn't work

### ISSUE THREAD

**Issue by Uefi1** [morrownr/8821cu#18]
Hello, some software unfortunately does not work with this driver :(((
1. Gemenis Auditor
2. Fern WiFi Cracker
3. Linset
4. Handshaker
5. WiFi Metropolis
You can somehow fix the driver to work with these tools ??

**Comment by morrownr** [comment]
Hello @Uefi1 

I am not familiar with any of those programs. I'll take a guess that maybe this has something to do with pen testing or something close to that? If so, you need good solid monitor mode performance. Right?

If that is the case, only 2 of the 5 Realtek drivers I maintain have good enough monitor mode support to be of any use: rtl8812au and rtl8821au. This driver is used by many people but I think it is almost exclusively used in managed mode.

The best thing I can do for you is make suggestions:

{USB WiFi Adapter Performance Comparison}(https://github.com/morrownr/USB-WiFi/blob/main/USB%20WiFi%20Adapter%20Performance%20Comparison.md)

[Monitor Mode Testing](https://github.com/morrownr/7612u/blob/main/Monitor_Mode.md)

[USB-WiFi](https://github.com/morrownr/USB-WiFi)

Take close look at the ALFA AWUS036ACHM. The range and signal quality is excellent.

Regards

**Comment by Uefi1** [comment]
> Hello @Uefi1
> 
> I am not familiar with any of those programs. I'll take a guess that maybe this has something to do with pen testing or something close to that? If so, you need good solid monitor mode performance. Right?
> 
> If that is the case, only 2 of the 5 Realtek drivers I maintain have good enough monitor mode support to be of any use: rtl8812au and rtl8821au. This driver is used by many people but I think it is almost exclusively used in managed mode.
> 
> The best thing I can do for you is make suggestions:
> 
> [USB WiFi Adapter Performance Comparison](https://github.com/morrownr/USB-WiFi/blob/main/USB%20WiFi%20Adapter%20Performance%20Comparison.md)
> 
> [Monitor Mode Testing](https://github.com/morrownr/7612u/blob/main/Monitor_Mode.md)
> 
> [USB-WiFi](https://github.com/morrownr/USB-WiFi)
> 
> Take a close look at the ALFA AWUS036ACHM. The range and signal quality is excellent.
> 
> Regards
Yes this is soft used for pentesting WiFi

**Comment by Uefi1** [comment]
It's not about the monitor mode, but simply do not see the adapter itself ((

**Comment by morrownr** [comment]
So, it isn't an issue with specific software, it is an issue with the adapter not being available.

Give me the results of:

$ lsusb

**Comment by Uefi1** [comment]
> So, it isn't an issue with specific software, it is an issue with the adapter not being available.
> 
> Give me the results of:
> 
> $ lsusb

Sorry my bad english, i meant that these programs do not see the adapter, but some programs still work for example wifiphisher, fluxion, oneshot, wifi-autopwner

**Comment by morrownr** [comment]
Quote: "Bus 002 Device 006: ID 0bda:c811 Realtek Semiconductor Corp. 802.11ac NIC"

Reply: The ID tells me this is an adapter adapter based on the 8811cu chipset so this repo is the correct driver. You can check this by looking at the file called "supported-device-IDs" in this repo.

Tell me what computer hardware you are using?

Tell me what operating system you are using?

Run the following and paste the results?

$ iw dev

$ lsmod

**Comment by Uefi1** [comment]
> Цитата: «Устройство шины 002 006: ID 0bda: c811 Realtek Semiconductor Corp. 802.11ac NIC»
> 
> Ответ: Идентификатор говорит мне, что это адаптер-адаптер на базе набора микросхем 8811cu, поэтому это репозиторий является правильным драйвером. Вы можете проверить это, посмотрев на файл с названием «supported-device-IDs» в этом репо.
> 
> Скажите, какое компьютерное оборудование вы используете?
> 
> Скажите, какую операционную систему вы используете?
> 
> Выполните следующее и вставьте результаты?
> 
> $ iw dev
> 
> $ lsmod

1. USB Adapter Terow - https://alitools.io/en/showcase/terow-usb-wifi-adapter-600mbps-2-4ghz-5-8ghz-wifi-receiver-wireless-network-card-usb2-0-wi-fi-high-speed-antenna-wifi-adapter-1005001884223023
2. Kali Linux
3. 
$ iw dev
phy#0
        Interface wlan0
                ifindex 3
                wdev 0x1
                addr d6:4a:2c:d6:d7:78
                type managed
                txpower 12.00 dBm


$ lsmod

Module                  Size  Used by
8821cu               2519040  0
cfg80211              974848  1 8821cu
intel_rapl_msr         20480  0
intel_rapl_common      28672  1 intel_rapl_msr
x86_pkg_temp_thermal    20480  0
intel_powerclamp       20480  0
snd_hda_codec_realtek   143360  1
snd_hda_codec_generic    98304  1 snd_hda_codec_realtek
coretemp               20480  0
kvm_intel             327680  0
ledtrig_audio          16384  1 snd_hda_codec_generic
snd_hda_codec_hdmi     73728  1
kvm                   913408  1 kvm_intel
snd_hda_intel          57344  3
snd_intel_dspcfg       24576  1 snd_hda_intel
soundwire_intel        45056  1 snd_intel_dspcfg
soundwire_generic_allocation    16384  1 soundwire_intel
snd_soc_core          315392  1 soundwire_intel
joydev                 28672  0
irqbypass              16384  1 kvm
snd_cmipci             49152  2
rapl                   20480  0
snd_compress           32768  1 snd_soc_core
soundwire_cadence      36864  1 soundwire_intel
snd_mpu401_uart        16384  1 snd_cmipci
intel_cstate           20480  0
snd_hda_codec         172032  4 snd_hda_codec_generic,snd_hda_codec_hdmi,snd_hda_intel,snd_hda_codec_realtek
snd_opl3_lib           20480  1 snd_cmipci
gameport               20480  1 snd_cmipci
intel_uncore          176128  0
snd_rawmidi            45056  1 snd_mpu401_uart
snd_seq_device         16384  2 snd_opl3_lib,snd_rawmidi
snd_hda_core          110592  5 snd_hda_codec_generic,snd_hda_codec_hdmi,snd_hda_intel,snd_hda_codec,snd_hda_codec_realtek
ppdev                  24576  0
snd_hwdep              16384  2 snd_hda_codec,snd_opl3_lib
soundwire_bus          90112  3 soundwire_intel,soundwire_generic_allocation,soundwire_cadence
snd_pcm               135168  8 snd_hda_codec_hdmi,snd_hda_intel,snd_hda_codec,soundwire_intel,snd_compress,snd_soc_core,snd_cmipci,snd_hda_core
mei_wdt                16384  0
iTCO_wdt               16384  0
intel_pmc_bxt          16384  1 iTCO_wdt
iTCO_vendor_support    16384  1 iTCO_wdt
at24                   24576  0
sg                     36864  0
watchdog               28672  2 iTCO_wdt,mei_wdt
serio_raw              20480  0
snd_timer              49152  2 snd_opl3_lib,snd_pcm
snd                   110592  25 snd_hda_codec_generic,snd_seq_device,snd_hda_codec_hdmi,snd_hwdep,snd_hda_intel,snd_hda_codec,snd_hda_codec_realtek,snd_opl3_lib,snd_timer,snd_compress,snd_soc_core,snd_mpu401_uart,snd_cmipci,snd_pcm,snd_rawmidi
parport_pc             40960  0
soundcore              16384  1 snd
eeepc_wmi              16384  0
parport                69632  2 parport_pc,ppdev
evdev                  28672  19
mei_me                 45056  1
asus_wmi               45056  1 eeepc_wmi
mei                   139264  3 mei_wdt,mei_me
battery                20480  1 asus_wmi
sparse_keymap          16384  1 asus_wmi
pcspkr                 16384  0
rfkill                 28672  5 asus_wmi,cfg80211
wmi_bmof               16384  0
binfmt_misc            24576  1
sunrpc                663552  1
fuse                  167936  7
configfs               57344  1
ip_tables              32768  0
x_tables               53248  1 ip_tables
autofs4                53248  2
squashfs               69632  1
loop                   36864  2
overlay               143360  1
nls_ascii              16384  1
nls_cp437              20480  1
vfat                   20480  1
fat                    86016  1 vfat
uas                    32768  0
usb_storage            81920  2 uas
hid_generic            16384  0
usbhid                 65536  0
hid                   147456  2 usbhid,hid_generic
sd_mod                 61440  5
t10_pi                 16384  1 sd_mod
sr_mod                 28672  0
crc_t10dif             20480  1 t10_pi
cdrom                  73728  1 sr_mod
crct10dif_generic      16384  0
crct10dif_pclmul       16384  1
crct10dif_common       16384  3 crct10dif_generic,crc_t10dif,crct10dif_pclmul
crc32_pclmul           16384  0
crc32c_intel           24576  0
ghash_clmulni_intel    16384  0
i2c_i801               32768  0
ahci                   40960  2
libahci                45056  1 ahci
aesni_intel           372736  0
libaes                 16384  1 aesni_intel
i2c_smbus              20480  1 i2c_i801
crypto_simd            16384  1 aesni_intel
libata                290816  2 libahci,ahci
cryptd                 24576  2 crypto_simd,ghash_clmulni_intel
glue_helper            16384  1 aesni_intel
i915                 2711552  6
scsi_mod              262144  6 sd_mod,usb_storage,uas,libata,sg,sr_mod
i2c_algo_bit           16384  1 i915
xhci_pci               20480  0
drm_kms_helper        274432  1 i915
r8169                  98304  0
cec                    61440  2 drm_kms_helper,i915
ehci_pci               20480  0
realtek                24576  1
xhci_hcd              307200  1 xhci_pci
mdio_devres            16384  1 r8169
lpc_ich                28672  0
ehci_hcd               98304  1 ehci_pci
libphy                151552  3 r8169,mdio_devres,realtek
usbcore               323584  8 xhci_hcd,ehci_pci,usbhid,8821cu,usb_storage,ehci_hcd,xhci_pci,uas
drm                   618496  6 drm_kms_helper,i915
usb_common             16384  3 xhci_hcd,usbcore,ehci_hcd
wmi                    36864  2 asus_wmi,wmi_bmof
fan                    20480  0
video                  53248  2 asus_wmi,i915
button                 24576  0
4. I take Linset from the repository
https://github.com/vk496/linset

**Comment by morrownr** [comment]
Quote: "8821cu 2519040 0"

The driver is loading.

Quote: "Interface wlan0"

The interface is being created.

All indications are that things are working. Can you tell me what steps you are taking to do what you want and what the result is?

**Comment by Uefi1** [comment]
> All indications are that things are working. Can you tell me what steps you are taking to do what you want and what the result is?
The adapter itself works, but some software that I listed in the first message does not work with it (
Console:
cd 8821cu-5.8.1.7
sudo make
sudo make install
sudo modprobe 8821cu
sudo git clone https://github.com/vk496/linset
cd linset
sudo chmod +x linset
sudo ./linset

Autodetect Resolution...
1920x1080

No wireless cards found. Closing...

[] Executing cleaning and closing.
[-] Cleaning iptables
[-] Restoring tput
[-] Deleting files
[-] Restarting NetworkManager
[+] Cleaning carried out successfully!

**Comment by morrownr** [comment]
Quote: "The adapter itself works, but some software that I listed in the first message does not work with it ("

I see. In that case all I can do is give you some general guidance:

- Realtek's out-of-kernel drivers are not Linux Wireless standards compliant. This can and does show up in many places. If the person writing the app is working with standards compliant drivers then that might explain why this driver is not working with a specific app.

- I have time to keep these drivers up to date with the latest changes in the Linux kernel and to do some minor fixing and additions but chasing down specific issues in specialized apps that I don't use will likely never make it to the top of my to-do list.

- Ask the authors of the apps what drivers they are using.

Good luck.

**Comment by Uefi1** [comment]
> Quote: "The adapter itself works, but some software that I listed in the first message does not work with it ("
> 
> I see. In that case all I can do is give you some general guidance:
> 
> * Realtek's out-of-kernel drivers are not Linux Wireless standards compliant. This can and does show up in many places. If the person writing the app is working with standards compliant drivers then that might explain why this driver is not working with a specific app.
> * I have time to keep these drivers up to date with the latest changes in the Linux kernel and to do some minor fixing and additions but chasing down specific issues in specialized apps that I don't use will likely never make it to the top of my to-do list.
> * Ask the authors of the apps what drivers they are using.
> 
> Good luck.

I have a disk with drivers for 8811 / 8821cu there and some sources can somehow help you to make the driver better if I provide an image of this disk?

**Comment by morrownr** [comment]
Quote: "I have a disk with drivers for 8811 / 8821cu..."

Reply: That would not help. The driver here is based on the most modern source code release available for the 8811/8821cu. The version on the disk would require a LOT of work just to get it to compile on modern kernels and in the end, it would not solve anything. Sending out Linux drivers on a CD is a sign that the adapter maker does understand how Linux driver support works... or they just don't care.

I started this site and the many repos in it as a way to help fellow Linux users that were having problems with Realtek USB WiFi drivers. It did not take long to learn that most Linux users were not aware of the adapters and chipsets that are supported in the Linux kernel. Having an adapter that uses an in-kernel driver is a game changer. To help people better understand how to get to USB WiFi happiness, I started a repo with a LOT of information. It explains the situation and even gives links to adapters that use in-kernel drivers. I think the information could be very helpful to you. I would help if it was something reasonable for me to do but it is not. I understand that you do not understand what you are asking me to do. Here is the site:

https://github.com/morrownr/USB-WiFi

**Comment by Uefi1** [comment]
> Quote: "I have a disk with drivers for 8811 / 8821cu..."
> 
> Reply: That would not help. The driver here is based on the most modern source code release available for the 8811/8821cu. The version on the disk would require a LOT of work just to get it to compile on modern kernels and in the end, it would not solve anything. Sending out Linux drivers on a CD is a sign that the adapter maker does understand how Linux driver support works... or they just don't care.
> 
> I started this site and the many repos in it as a way to help fellow Linux users that were having problems with Realtek USB WiFi drivers. It did not take long to learn that most Linux users were not aware of the adapters and chipsets that are supported in the Linux kernel. Having an adapter that uses an in-kernel driver is a game changer. To help people better understand how to get to USB WiFi happiness, I started a repo with a LOT of information. It explains the situation and even gives links to adapters that use in-kernel drivers. I think the information could be very helpful to you. I would help if it was something reasonable for me to do but it is not. I understand that you do not understand what you are asking me to do. Here is the site:
> 
> https://github.com/morrownr/USB-WiFi

Please understand why Linset and Handshaker do not work with your driver
Linset:
https://github.com/vk496/linset
Handshaker:
https://github.com/d4rkcat/HandShaker
The code in them is completely open

**Comment by Uefi1** [comment]
> I took a look at Linset. It appears the code hasn't been touched in around 7 years. That is a bad sign for something that makes heavy use of the networking stack. Explain to me why you think the problem is with this driver.
I think that the problem is in the driver because Linset works with the old tp-link adapter

**Comment by morrownr** [comment]
What chipset is in the old to-link adapter?

**Comment by morrownr** [comment]
The driver for that ar9271 is in the kernel and is Linux Wireless standards compliant. I can see why it still works.

My opinion, if you want these apps to work with modern dual band adapters is to look at adapters that have in-kernel drivers that are standards compliant.

https://github.com/morrownr/USB-WiFi

I might have time one of these days to take a deeper look but it will probably be next fall at the earliest.

**Comment by Uefi1** [comment]
> I might have time one of these days to take a deeper look but it will probably be next fall at the earliest.

Thank you very much for your responsiveness!

**Comment by morrownr** [comment]
I wish you luck. You are looking at a lot of work to get things going like you want. Later this year i might have time to engage but not right now.
