### ISSUE TITLE
device over heat and the ofline

### ISSUE THREAD

**Issue by yufalcon** [morrownr/8821cu#2]
hi developer my device is rtl8811cu & device over heat and the ofline

any solution?

**Comment by morrownr** [comment]
yufalcon, this is the correct driver for the rtl8811cu chipset. My test adapter uses the rtl8811cu chipset. I have not seen any overheating here. Can you be specific about the adapter that you have?

**Comment by yufalcon** [comment]
> yufalcon, this is the correct driver for the rtl8811cu chipset. My test adapter uses the rtl8811cu chipset. I have not seen any overheating here. Can you be specific about the adapter that you have?

like this https://www.youtube.com/watch?v=JlF7I2CCO6U but i connnect to ap cisco support with 5ghz ac and link speed detected is 150 Mbps

**Comment by morrownr** [comment]
Okay, I watched a little of the video. I speak English and Spanish only so could not understand what was said. Questions:

Is your device a USB adapter? This driver is compiled for USB adapters.

What operating system are you using?

**Comment by yufalcon** [comment]
> Okay, I watched a little of the video. I speak English and Spanish only so could not understand what was said. Questions:
> 
> Is your device a USB adapter? This driver is compiled for USB adapters.
> 
> What operating system are you using?

yes , i use parrot os

**Comment by morrownr** [comment]
If your adapter has an LED, you could turn it off. See Driver Options section in README. That could save a little heat.

I'm really at a loss. I was using my adapter earlier and it stays cool even under a heavy load...and it is a nano adapter with little space to help with cooling.

**Comment by morrownr** [comment]
Issue closed due to no further information for over one week. Issue can be reopened if required.
