### ISSUE TITLE
(solved) remove-driver.sh will removes all your home directory

### ISSUE THREAD

**Issue by sivinnguyen** [morrownr/8821cu#22]
The cmd `rm -rf ${DRV_DIR}` in remove-driver.sh will remove the whole of home directory (folders, configuration files...) and need to reinstall os.

**Comment by morrownr** [comment]
What you say is possible if you do not follow the posted usage instructions.

**Comment by morrownr** [comment]
I have changed the following statement in remove-driver.sh ...

DRV_DIR="$(pwd)"

to

DRV_DIR="~/src/8821cu"

Hopefully that prevents any problems in the future. If you see a better way, let me know.

**Comment by sivinnguyen** [comment]
> I have changed the following statement in remove-driver.sh ...
> 
> DRV_DIR="$(pwd)"
> 
> to
> 
> DRV_DIR="~/src/8821cu"
> 
> Hopefully that prevents any problems in the future. If you see a better way, let me know.

Thanks. I think should not remove source folder, because you have to download it again every time you reinstall driver ^^
