### ISSUE TITLE
Driver does not work

### ISSUE THREAD

**Issue by KSPAtlas** [morrownr/8821cu#26]
So, I have a Realtek rtl8821cu. I have an Artix install, and I install the dkms module. Nothing changes, trying to do a "scan wifi" gives me a not supported error from connman.

**Comment by morrownr** [comment]
Hi,

Can you provide some information about Artix so that I know what I'm dealing with? Hardware info would probably be helpful also.

Quote: "I install the dkms module"

Okay, but did you follow the installation instructions?

**Comment by KSPAtlas** [comment]
Turns out all I had to do was unplug the USB before installing the drivet

**Comment by morrownr** [comment]
You are welcome to close the issue if the driver is working.
