### ISSUE TITLE
Error in kernel 5.15 with RPI4B

### ISSUE THREAD

**Issue by matalama80td3l** [morrownr/8821cu#36]
`Building module:
cleaning build area...
'make' -j4 KVER=5.15.1-v8+ KSRC=/lib/modules/5.15.1-v8+/build.......................................................(bad exit status: 2)
Error! Bad return status for module build on kernel: 5.15.1-v8+ (aarch64)
Consult /var/lib/dkms/rtl8821cu/5.8.1.7/build/make.log for more information.
An error occurred. dkms build error = 10
Please report this error.
`
And here's error in /var/lib/dkms/rtl8821cu/5.8.1.7/build/make.log.
`ERROR: modpost: "module_layout" [/var/lib/dkms/rtl8821cu/5.8.1.7/build/8821cu.ko] undefined!
ERROR: modpost: "usb_register_driver" [/var/lib/dkms/rtl8821cu/5.8.1.7/build/8821cu.ko] undefined!
ERROR: modpost: "__napi_schedule" [/var/lib/dkms/rtl8821cu/5.8.1.7/build/8821cu.ko] undefined!
ERROR: modpost: "strsep" [/var/lib/dkms/rtl8821cu/5.8.1.7/build/8821cu.ko] undefined!
ERROR: modpost: "eth_type_trans" [/var/lib/dkms/rtl8821cu/5.8.1.7/build/8821cu.ko] undefined!
ERROR: modpost: "cfg80211_external_auth_request" [/var/lib/dkms/rtl8821cu/5.8.1.7/build/8821cu.ko] undefined!
ERROR: modpost: "napi_gro_receive" [/var/lib/dkms/rtl8821cu/5.8.1.7/build/8821cu.ko] undefined!
ERROR: modpost: "register_netdevice_notifier" [/var/lib/dkms/rtl8821cu/5.8.1.7/build/8821cu.ko] undefined!
ERROR: modpost: "napi_enable" [/var/lib/dkms/rtl8821cu/5.8.1.7/build/8821cu.ko] undefined!
ERROR: modpost: "strlen" [/var/lib/dkms/rtl8821cu/5.8.1.7/build/8821cu.ko] undefined!
WARNING: modpost: suppressed 172 unresolved symbol warnings because there were too many)
make[2]: *** [scripts/Makefile.modpost:134：/var/lib/dkms/rtl8821cu/5.8.1.7/build/Module.symvers] 错误 1
make[2]: *** 正在删除文件“/var/lib/dkms/rtl8821cu/5.8.1.7/build/Module.symvers”
make[1]: *** [Makefile:1783：modules] 错误 2
make[1]: 离开目录“/home/pi/linux-f27b6539b89b6245a458c139767eac8e2e51e8f0”
make: *** [Makefile:2374：modules] 错误 2
`
Sorry about there's Chinese in it. I think this dosen't matter.
错误=error. 正在删除文件=deleting file. 离开目录=leaving dir

**Comment by morrownr** [comment]
I understand kernel 5.15 and RasPi4B but...

What operating system and version are your using?

Did you run raspi32.sh or raspi64.sh?
